### ISSUE TITLE
Showstopping bug if too many users/orgs are processed

### ISSUE THREAD

**Issue by jlarmstrongiv** [jlarmstrongiv/github-clone-all-repos#1]
Console erroring
```
Querying Github…
 · Unable to find any repositories for heymichaelwm
failed:  TypeError: Cannot read property 'on' of undefined
    at Git._schedule (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1272:24)
    at Git._run (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1250:12)
    at Git.clone (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:186:19)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:28:21
    at Promise (<anonymous>)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:18:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
failed:  TypeError: Cannot read property 'on' of undefined
    at Git._schedule (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1272:24)
    at Git._run (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1250:12)
    at Git.clone (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:186:19)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:28:21
    at Promise (<anonymous>)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:18:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
failed:  TypeError: Cannot read property 'on' of undefined
    at Git._schedule (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1272:24)
    at Git._run (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1250:12)
    at Git.clone (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:186:19)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:28:21
    at Promise (<anonymous>)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:18:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
failed:  TypeError: Cannot read property 'on' of undefined
    at Git._schedule (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1272:24)
    at Git._run (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1250:12)
    at Git.clone (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:186:19)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:28:21
    at Promise (<anonymous>)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:18:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
failed:  TypeError: Cannot read property 'on' of undefined
    at Git._schedule (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1272:24)
    at Git._run (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:1250:12)
    at Git.clone (/usr/local/lib/node_modules/gcar/node_modules/simple-git/src/git.js:186:19)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:28:21
    at Promise (<anonymous>)
    at /usr/local/lib/node_modules/gcar/node_modules/simple-git/promise.js:18:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by jlarmstrongiv** [comment]
More error logs
```
Error: spawn git EAGAIN
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by jlarmstrongiv** [comment]
Even more error logs
```
events.js:182
      throw er; // Unhandled 'error' event
      ^
```
